# Generated by Django 5.0.6 on 2025-04-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=255)),
                ("action_owner", models.CharField(max_length=255)),
                ("sop", models.CharField(max_length=255)),
                ("topics", models.CharField(max_length=255)),
                ("vertical", models.CharField(max_length=255)),
                ("sop_steps", models.TextField()),
                ("training_and_task_start", models.DateTimeField()),
                ("action_step", models.TextField()),
                ("Deadline_1", models.CharField(max_length=255)),
                ("assessment_1", models.TextField()),
                ("Deadline_2", models.CharField(max_length=255)),
                ("assessment_2", models.TextField()),
                ("sop_status", models.BooleanField()),
                ("team_assessment", models.TextField()),
                ("no_of_deadline", models.IntegerField()),
                ("total_sop_step", models.IntegerField()),
                ("done_sop_step_number", models.IntegerField()),
                ("sop_percentage", models.FloatField()),
                ("frequency", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                (
                    "sops",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_categories",
                        to="sops.sops",
                    ),
                ),
            ],
        ),
    ]
