# Generated by Django 5.0.6 on 2025-04-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0002_sops_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sops",
            name="department",
            field=models.CharField(
                choices=[("operation", "operation"), ("maintenance", "Maintenance")],
                default="operation",
                max_length=255,
            ),
        ),
    ]
