# Generated by Django 5.0.6 on 2025-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0003_alter_sops_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sops",
            name="Deadline_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sops",
            name="Deadline_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sops",
            name="team_assessment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
