# Generated by Django 5.0.6 on 2025-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0004_alter_sops_deadline_1_alter_sops_deadline_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sops",
            name="no_of_deadline",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
