# Generated by Django 5.0.6 on 2025-04-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0005_alter_sops_no_of_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sops",
            name="sop_steps",
        ),
        migrations.CreateModel(
            name="SopStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "sop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="sops.sops",
                    ),
                ),
            ],
        ),
    ]
