# Generated by Django 5.0.6 on 2025-04-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0006_remove_sops_sop_steps_sopstep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sops",
            name="sop_status",
        ),
        migrations.AddField(
            model_name="city",
            name="sop_status",
            field=models.BooleanField(default=True),
        ),
    ]
