# Generated by Django 5.0.6 on 2025-04-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0007_remove_sops_sop_status_city_sop_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sops",
            name="action_step",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sops",
            name="assessment_1",
            field=models.TextField(blank=True, null=True),
        ),
    ]
