# Generated by Django 5.0.6 on 2025-04-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0008_alter_sops_action_step_alter_sops_assessment_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sops",
            name="sop_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
