# Generated by Django 5.0.6 on 2025-04-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0009_alter_sops_sop_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sops",
            name="assessment_2",
            field=models.TextField(blank=True, null=True),
        ),
    ]
