# Generated by Django 5.0.6 on 2025-04-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0010_alter_sops_assessment_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="sops",
            name="in_working",
            field=models.BooleanField(default=False),
        ),
    ]
