# Generated by Django 5.0.6 on 2025-04-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sops", "0011_sops_in_working"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="sops",
        ),
        migrations.AddField(
            model_name="sops",
            name="cities",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="sops", to="sops.city"
            ),
        ),
    ]
