# Generated by Django 4.2.23 on 2025-06-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DustbinCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=159)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatedsop.dustbincity')),
            ],
        ),
        migrations.CreateModel(
            name='DetectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_dustbin_fill_in_start_top_view', models.ImageField(upload_to='uploads/')),
                ('is_dustbin_fill_in_start_top_view_ok', models.BooleanField(default=False)),
                ('is_any_trash_detected_near_dustbin', models.ImageField(upload_to='uploads/')),
                ('is_any_trash_detected_near_dustbin_ok', models.BooleanField(default=False)),
                ('after_removing_trash_from_inside', models.ImageField(upload_to='uploads/')),
                ('after_removing_trash_from_inside_ok', models.BooleanField(default=False)),
                ('after_removed_trash_near_from_dustbin', models.ImageField(upload_to='uploads/')),
                ('after_removed_trash_near_from_dustbin_ok', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatedsop.zone')),
            ],
        ),
    ]
