# Generated by Django 4.2.23 on 2025-07-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatedsop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('trip_number', models.CharField(max_length=20)),
                ('driver_id', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_number', models.CharField(max_length=100)),
                ('image01_state', models.CharField(max_length=100)),
                ('image02_state', models.CharField(max_length=100)),
                ('image03_state', models.CharField(max_length=100)),
                ('image04_state', models.CharField(max_length=100)),
                ('image01_path', models.URLField()),
                ('image02_path', models.URLField()),
                ('image03_path', models.URLField()),
                ('image04_path', models.URLField()),
                ('image01_correct', models.BooleanField(default=False)),
                ('image02_correct', models.BooleanField(default=False)),
                ('image03_correct', models.BooleanField(default=False)),
                ('image04_correct', models.BooleanField(default=False)),
                ('remark', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
