# Generated by Django 4.2.23 on 2025-07-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatedsop', '0002_tripvalidationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('expected_amount', models.FloatField(blank=True, null=True)),
                ('expected_volume', models.FloatField(blank=True, null=True)),
                ('extracted_text', models.TextField()),
                ('amount_match', models.BooleanField(default=False)),
                ('volume_match', models.BooleanField(default=False)),
                ('image_path', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
