# Generated by Django 4.2.23 on 2025-07-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatedsop', '0003_fuelvalidationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSOPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('violation', models.TextField(blank=True)),
                ('is_sop_followed', models.BooleanField(default=True)),
            ],
        ),
    ]
