# Generated by Django 5.2.6 on 2025-09-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatedsop', '0004_employeesopreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkipLinesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_key', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('line_no', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('LineCompleted', 'Completed'), ('Skipped', 'Skipped'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('repeated', models.BooleanField(default=False)),
                ('driver_id', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('driver_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('helper_id', models.CharField(blank=True, max_length=100, null=True)),
                ('helper_name', models.CharField(blank=True, max_length=200, null=True)),
                ('helper_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
            ],
        ),
    ]
